name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Archive binary
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/upstream-rs* dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upstream-rs${{ matrix.target }}
          path: dist/*
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
